### ISSUE TITLE
Coloured output

### ISSUE THREAD

**Issue by joshhopkins** [p1g30n/explainshell-cli#1]
Nice work with this! Would be great if the output was coloured, similar to the website.

**Comment by thepigeonoftime** [comment]
Hey, I have a half finished version with colored output lying around but hadn't yet had the time to test all the edge cases, you can find it in the [https://github.com/p1g30n/explainshell-cli/tree/colored](https://github.com/p1g30n/explainshell-cli/tree/colored) branch, happy over some feedback, especially regarding the styling (I'm limited to the colors/styles listed here https://github.com/mackwic/colored )
